module.exports = {
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    parserOptions: {
        parser: '@typescript-eslint/parser',
        ecmaVersion: 12,
        sourceType: 'module',
    },
    plugins: [
        '@typescript-eslint',
    ],
    rules: {
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/consistent-type-imports': 'error',
        '@typescript-eslint/explicit-member-accessibility': ['error', { overrides: { constructors: 'off' } }],
        '@typescript-eslint/explicit-module-boundary-types': 'error',
        '@typescript-eslint/func-call-spacing': ['error', 'never'],
        '@typescript-eslint/member-delimiter-style': 'error',
        '@typescript-eslint/no-duplicate-imports': 'error',
        '@typescript-eslint/no-empty-interface': 'off',
        '@typescript-eslint/no-explicit-any': ['warn', { ignoreRestArgs: true }],
        '@typescript-eslint/no-inferrable-types': 'off',
        '@typescript-eslint/no-this-alias': 'off',
        '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_+$' }],
        '@typescript-eslint/semi': ['error', 'always'],
        '@typescript-eslint/space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
        'array-bracket-spacing': 'error',
        'comma-dangle': ['error', 'always-multiline'],
        'function-call-argument-newline': ['error', 'consistent'],
        'function-paren-newline': ['error', 'multiline-arguments'],
        'indent': ['error', 4, { SwitchCase: 1 }],
        'key-spacing': 'error',
        'linebreak-style': ['error', 'unix'],
        'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
        'max-len': ['error', 120],
        'no-console': 'error',
        'no-multi-spaces': ['error', { exceptions: { Property: false } }],
        'no-unused-vars': 'off',
        'object-curly-newline': ['error', { ImportDeclaration: { multiline: true } }],
        'object-curly-spacing': ['error', 'always'],
        'padded-blocks': ['error', { blocks: 'never', classes: 'always', switches: 'never' }],
        'quote-props': ['error', 'consistent-as-needed'],
        'quotes': ['error', 'single'],
        'semi': 'off',
        'sort-imports': ['error', { allowSeparatedGroups: true, ignoreDeclarationSort: true }],
        'space-before-function-paren': 'off',
        'space-in-parens': 'error',
        'space-infix-ops': 'error',
    },
    overrides: [
        {
            files: ['*.js'],
            env: { node: true },
            rules: {
                '@typescript-eslint/no-var-requires': 'off',
            },
        },
        {
            files: ['*.test.ts', '*.spec.ts'],
            rules: {
                'padded-blocks': ['error', { classes: 'always', switches: 'never' }],
            },
        },
    ],
    ignorePatterns: [
        'dist/*',
        'tmp/*',
    ],
};
