name: CI

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: CI
              run: |
                cd noeldemartin
                npm ci
                npm run build
                npm run lint
                npm test
